---
- name: Generate Kubernetes join token on controller
  hosts: kubernetes_controller
  become: yes
  tasks:
    - name: Create join token
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Display join command
      debug:
        msg: "Join command: {{ join_command.stdout }}"

    - name: Save join command to file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /tmp/kubeadm_join_command.txt
